# Generated by Django 3.1.2 on 2020-10-06 16:53

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201005_2352'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', chat.models.CustomUser()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(upload_to='profilePhoto'),
        ),
    ]
