# Generated by Django 3.1.2 on 2020-10-06 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users_lists',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
